-- India Stock Tracker v2 — universe table seed
-- Exported live from the v2 Supabase project on 2026-09-12 (full table, all rows, both
-- active and inactive). Supersedes Starting Point/nifty500_universe.sql, which is a v1-era
-- seed and out of date relative to this. Run against a fresh `universe` table (see
-- docs/03-ai-rebuild-spec.md §3 for the CREATE TABLE this expects to already exist).
--
-- KNOWN DATA ANOMALY, left as-is rather than silently corrected: the row for CPPLUS
-- ("Aditya Infotech Ltd") is stored as 'NSE:CPPLUS' — WITH the exchange prefix — unlike
-- every other row in this table, which are all bare tickers (e.g. 'ABB', not 'NSE:ABB').
-- This is a genuine inconsistency in the live data, not a transcription error here. Fix it
-- with `update universe set ticker = 'CPPLUS' where ticker = 'NSE:CPPLUS';` if you want the
-- table fully consistent — not done automatically as part of this seed file.

insert into universe (ticker, stock_name, exchange, active) values ('360ONE', '360 One WAM', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('3MINDIA', '3M India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AADHARHFC', 'Aadhar Housing Finance Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AARTIIND', 'Aarti Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AARTIPHARM', 'Aarti Pharmalabs', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AAVAS', 'Aavas Financiers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABB', 'ABB India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABBOTINDIA', 'Abbott India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABCAPITAL', 'Aditya Birla Capital', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABDL', 'Allied Blenders and Distillers Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABFRL', 'Aditya Birla Fashion', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABLBL', 'Aditya Birla Lifestyle Brands Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABREL', 'Aditya Birla Real Estate Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABSLAMC', 'Aditya Birla Sun Life AMC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ABSLBANETF', 'Aditya Birla Nifty ETF', 'NSE', 'f');
insert into universe (ticker, stock_name, exchange, active) values ('ACC', 'ACC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ACCELYA', 'Accelya Solutions', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ACE', 'Action Construction Equipment', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ACMESOLAR', 'ACME Solar Holdings Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ACUTAAS', 'Acutaas Chemicals Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ADANIENSOL', 'Adani Energy Solutions', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ADANIENT', 'Adani Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ADANIGREEN', 'Adani Green Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ADANIPORTS', 'Adani Ports', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ADANIPOWER', 'Adani Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AEGISLOG', 'Aegis Logistics Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AEGISVOPAK', 'Aegis Vopak Terminals Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AFCONS', 'Afcons Infrastructure Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AFFLE', 'Affle India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AIAENG', 'AIA Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AIIL', 'Authum Investment & Infrastructure Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AJANTPHARM', 'Ajanta Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AJAXENG', 'Ajax Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AKZOINDIA', 'Akzo Nobel India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ALEMBICLTD', 'Alembic', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ALEMBICPH', 'Alembic Pharmaceuticals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ALKEM', 'Alkem Laboratories', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ALOKINDS', 'Alok Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AMARAJABAT', 'Amara Raja Energy', 'NSE', 'f');
insert into universe (ticker, stock_name, exchange, active) values ('AMBER', 'Amber Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AMBUJACEM', 'Ambuja Cements', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AMHHOLDING', 'AMH Holdings', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AMNPLST', 'Amines and Plasticizers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANANDRATHI', 'Anand Rathi Wealth Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANANTRAJ', 'Anant Raj', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANDHRSUGAR', 'Andhra Sugars', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANGELONE', 'Angel One', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANNAS', 'Anna Steel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANTHEM', 'Anthem Biosciences Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ANURAS', 'Anupam Rasayan', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APARINDS', 'Apar Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APLAPOLLO', 'APL Apollo Tubes', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APOLLOHOSP', 'Apollo Hospitals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APOLLOPIPE', 'Apollo Pipes', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APOLLOTYRE', 'Apollo Tyres', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('APTUS', 'Aptus Value Housing', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ARE&M', 'Amara Raja Energy & Mobility', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ARTSON', 'Artson Engineering', 'BSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ARVINDFASN', 'Arvind Fashions', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ARVSMART', 'Arvind SmartSpaces', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASAHIINDIA', 'Asahi India Glass', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASHAPURMIN', 'Ashapura Minechem', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASHOKLEY', 'Ashok Leyland', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASIANENE', 'Asian Energy Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASIANHOTNR', 'Asian Hotels North', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASIANPAINT', 'Asian Paints', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASMTEC', 'ASM Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASTERDM', 'Aster DM Healthcare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ASTRAL', 'Astral', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ATFL', 'Agro Tech Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ATGL', 'Adani Total Gas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ATHERENERG', 'Ather Energy Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ATUL', 'Atul', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AUBANK', 'AU Small Finance Bank Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AUROPHARMA', 'Aurobindo Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AVANTIFEED', 'Avanti Feeds', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AWFIS', 'Awfis Space Solutions Ltd', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AWL', 'AWL Agri Business Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('AXISBANK', 'Axis Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJ-AUTO', 'Bajaj Auto', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJELEC', 'Bajaj Electricals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJFINSV', 'Bajaj Finserv', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJHFL', 'Bajaj Housing Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJHIND', 'Bajaj Hindusthan Sugar', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJAJHLDNG', 'Bajaj Holdings & Investment Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAJFINANCE', 'Bajaj Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BALKRISIND', 'Balkrishna Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BALMLAWRIE', 'Balmer Lawrie', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BALRAMCHIN', 'Balrampur Chini Mills', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BANARISUG', 'Bannari Amman Sugars', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BANDHANBNK', 'Bandhan Bank Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BANKBARODA', 'Bank of Baroda', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BANKINDIA', 'Bank of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BATAINDIA', 'Bata India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BAYERCROP', 'Bayer CropScience', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BBOX', 'Black Box', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BBTC', 'Bombay Burmah Trading', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BCG', 'Brightcom Group', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BDL', 'Bharat Dynamics Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BEL', 'Bharat Electronics', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BELRISE', 'Belrise Industries Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BEML', 'BEML', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BERGEPAINT', 'Berger Paints', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BHARATFORG', 'Bharat Forge Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BHARTIARTL', 'Bharti Airtel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BHARTIHEXA', 'Bharti Hexacom Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BHEL', 'Bharat Heavy Electricals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BIKAJI', 'Bikaji Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BIOCON', 'Biocon Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BIRET', 'Brookfield India Real Estate Trust', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BIRLACORPN', 'Birla Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BLKASHYAP', 'B L Kashyap', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BLS', 'BLS International', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BLUEDART', 'Blue Dart Express Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BLUEJET', 'Blue Jet Healthcare Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BLUESTARCO', 'Blue Star', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BORORENEW', 'Boro Renewables', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BOSCHLTD', 'Bosch', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BPCL', 'BPCL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BRIGADE', 'Brigade Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BRITANNIA', 'Britannia Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BSE', 'BSE', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BSHSL', 'Bombay Super Hybrid Seeds', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('BSOFT', 'BFSI Sector', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CAMLINFINE', 'Camlin Fine Sciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CAMPUS', 'Campus Activewear', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CAMS', 'CAMS', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CANBK', 'Canara Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CANFINHOME', 'Can Fin Homes', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CANHLIFE', 'Canara HSBC Life Insurance Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CANOLAFS', 'Canola Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CAPLIPOINT', 'Caplin Point Laboratories', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CAPMFG', 'CAP Manufacturing', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CARBORUNIV', 'Carborundum Universal', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CARTRADE', 'Cartrade Tech Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CASTROLIND', 'Castrol India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CCL', 'CCL Products', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CDSL', 'CDSL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CEATLTD', 'CEAT', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CEMPRO', 'Cemindia Projects Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CENTRALBK', 'Central Bank of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CENTURYPLY', 'Century Plyboards', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CENTURYTEX', 'Century Textiles', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CERA', 'Cera Sanitaryware', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CESC', 'CESC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CGCL', 'Capri Global Capital Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CGPOWER', 'CG Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHALET', 'Chalet Hotels', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHAMBLFERT', 'Chambal Fertilizers & Chemicals Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHEMPLASTS', 'Chemplast Sanmar', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHENNPETRO', 'Chennai Petroleum Corporation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHOICEIN', 'Choice International Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHOLAFIN', 'Cholamandalam Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CHOLAHLDNG', 'Cholamandalam Financial Holdings', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CIEINDIA', 'CIE Automotive India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CIPLA', 'Cipla', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CLEAN', 'Clean Science', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COALINDIA', 'Coal India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COCHINSHIP', 'Cochin Shipyard Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COFORGE', 'Coforge', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COHANCE', 'Cohance Lifesciences Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COLPAL', 'Colgate-Palmolive', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CONCOR', 'Container Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CONCORDBIO', 'Concord Biotech Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('COROMANDEL', 'Coromandel International', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CRAFTSMAN', 'Craftsman Automation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CREDITACC', 'CreditAccess Grameen Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CRISIL', 'CRISIL Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CROMPTON', 'Crompton Greaves', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CUB', 'City Union Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CUMMINSIND', 'Cummins India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('CYIENT', 'Cyient Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DABUR', 'Dabur India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DALBHARAT', 'Dalmia Bharat', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DATAPATTNS', 'Data Patterns (India) Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DCAL', 'Dishman Carbogen Amcis', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DCBBANK', 'DCB Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DCMSHRIRAM', 'DCM Shriram Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DEEPAKFERT', 'Deepak Fertilisers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DEEPAKNTR', 'Deepak Nitrite', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DELHIVERY', 'Delhivery', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DELTACORP', 'Delta Corp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DEVYANI', 'Devyani International', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DHANI', 'Dhani Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DHANUKA', 'Dhanuka Agritech', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DHARMAJ', 'Dharmaj Crop Guard', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DHUNINV', 'Dhunseri Investments', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DISHTV', 'Dish TV India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DIVISLAB', 'Divis Laboratories', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DIXON', 'Dixon Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DLF', 'DLF', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DMART', 'Avenue Supermarts', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DOLLAR', 'Dollar Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DOMS', 'DOMS Industries Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DRREDDY', 'Dr Reddys Laboratories', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('DRSNLANKAH', 'Dr. Agarwals Eye Hospital', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ECLERX', 'eClerx Services Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EDELWEISS', 'Edelweiss Financial', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EICHERMOT', 'Eicher Motors', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EIDPARRY', 'E.I.D. Parry (India) Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EIHAHOTELS', 'EIH Associated Hotels', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EIHOTEL', 'EIH', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EIMCOELECO', 'Eimco Elecon', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ELECON', 'Elecon Engineering Co. Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ELGIEQUIP', 'Elgi Equipments', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EMAMILTD', 'Emami', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EMCURE', 'Emcure Pharmaceuticals Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EMMVEE', 'Emmvee Photovoltaic Power Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ENDURANCE', 'Endurance Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ENGINERSIN', 'Engineers India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ENRIN', 'Siemens Energy India Limited', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EPIGRAL', 'Epigral', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EQUITASBNK', 'Equitas Small Finance Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ERIS', 'Eris Lifesciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ESABINDIA', 'Esab India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ESCORTS', 'Escorts Kubota', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ESDEE', 'Esdee Varnish', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ETERNAL', 'Eternal', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ETHANOLBIO', 'Ethanol Biofuel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('EXIDEIND', 'Exide Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FACT', 'Fertilisers and Chemicals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FEDERALBNK', 'Federal Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FINCABLES', 'Finolex Cables', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FINEORG', 'Fine Organic Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FINOLEXIND', 'Finolex Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FIRSTCRY', 'Brainbees Solutions Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FIVESTAR', 'Five-Star Business Finance Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FLUOROCHEM', 'Gujarat Fluorochemicals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FMGOETZE', 'Federal-Mogul Goetze', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FORCEMOT', 'Force Motors Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FORTIS', 'Fortis Healthcare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('FSL', 'Firstsource Solutions Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GABRIEL', 'Gabriel India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GAIL', 'GAIL India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GALAXYSURF', 'Galaxy Surfactants', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GALLANTT', 'Gallantt Ispat Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GARFIBRES', 'Garware Technical Fibres', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GATECHDVR', 'Gateway Distriparks', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GESHIP', 'Great Eastern Shipping', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GICRE', 'GIC Re', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GILLETTE', 'Gillette India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GLAND', 'Gland Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GLAXO', 'GSK Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GLENMARK', 'Glenmark Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GMBREW', 'GM Breweries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GMDCLTD', 'Gujarat Mineral Development Corporation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GMRAIRPORT', 'GMR Airports', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GNFC', 'Gujarat Narmada Valley Fertilizers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODFRYPHLP', 'Godfrey Phillips', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODIGIT', 'Go Digit General Insurance Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODREJAGRO', 'Godrej Agrovet', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODREJCP', 'Godrej Consumer Products', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODREJIND', 'Godrej Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GODREJPROP', 'Godrej Properties', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GPIL', 'Godawari Power & Ispat', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GPPL', 'Gujarat Pipavav Port', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRANULES', 'Granules India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRAPHITE', 'Graphite India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRASIM', 'Grasim Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRAVITA', 'Gravita India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GREENPANEL', 'Greenpanel Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GREENPLY', 'Greenply Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRINDWELL', 'Grindwell Norton', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GROWW', 'Billionbrains Garage Ventures Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GRSE', 'Garden Reach Shipbuilders', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GSFC', 'Gujarat State Fertilizers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GSPL', 'Gujarat State Petronet', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GTLINFRA', 'GTL Infrastructure', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GUJALKALI', 'Gujarat Alkalies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GUJGASLTD', 'Gujarat Gas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GULFOILLUB', 'Gulf Oil Lubricants', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('GVT&D', 'GE Vernova T&D India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HAL', 'Hindustan Aeronautics', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HAPPSTMNDS', 'Happiest Minds Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HATSUN', 'Hatsun Agro Product', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HAVELLS', 'Havells India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HBLENGINE', 'HBL Engineering Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HCG', 'HealthCare Global Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HCLTECH', 'HCL Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HDBFS', 'HDB Financial Services Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HDFCAMC', 'HDFC AMC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HDFCBANK', 'HDFC Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HDFCLIFE', 'HDFC Life Insurance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HDFCWM', 'HDFC Wealth Management', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HEG', 'HEG Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HERITGFOOD', 'Heritage Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HEROMOTOCO', 'Hero MotoCorp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HEXT', 'Hexaware Technologies Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HFCL', 'HFCL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HIKAL', 'Hikal', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HINDALCO', 'Hindalco Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HINDCOPPER', 'Hindustan Copper', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HINDPETRO', 'HPCL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HINDUNILVR', 'Hindustan Unilever', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HINDZINC', 'Hindustan Zinc Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HLEGLAS', 'HLE Glascoat', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HOMEFIRST', 'Home First Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HONASA', 'Honasa Consumer Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HONAUT', 'Honeywell Automation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HSCL', 'Himadri Speciality Chemical Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HUDCO', 'Housing & Urban Development Corp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('HYUNDAI', 'Hyundai Motor India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IBREALEST', 'Indiabulls Real Estate', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ICICIAMC', 'ICICI Prudential Asset Management Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ICICIBANK', 'ICICI Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ICICIGI', 'ICICI Lombard', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ICICIPRULI', 'ICICI Prudential Life', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ICIL', 'Indo Count Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IDBI', 'IDBI Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IDEA', 'Vodafone Idea Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IDFC', 'IDFC', 'NSE', 'f');
insert into universe (ticker, stock_name, exchange, active) values ('IDFCFIRSTB', 'IDFC First Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IEX', 'Indian Energy Exchange', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IFBIND', 'IFB Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IFCI', 'IFCI', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IGIL', 'International Gemological Institute Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IGL', 'Indraprastha Gas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IIFL', 'IIFL Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IIFLFIN', 'IIFL Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IIFLWAM', 'IIFL Wealth Management', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IKS', 'Inventurus Knowledge Solutions Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IMFA', 'Indian Metals & Ferro Alloys', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDGN', 'Indowind Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDHOTEL', 'Indian Hotels', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIACEM', 'India Cements Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIAMART', 'IndiaMART InterMESH', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIANB', 'Indian Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIGO', 'IndiGo', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIGOPNTS', 'Indigo Paints', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDIGRID', 'Indigrid Infrastructure Trust', 'BSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDRAMEDCO', 'Indraprastha Medical', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDUSINDBK', 'IndusInd Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDUSINVIT', 'Indus Infra Trust', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INDUSTOWER', 'Indus Towers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INFY', 'Infosys', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INOXGREEN', 'INOX Green Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INOXWIND', 'Inox Wind', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('INTELLECT', 'Intellect Design Arena', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IOB', 'Indian Overseas Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IOC', 'Indian Oil Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IPCALAB', 'IPCA Laboratories', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IRB', 'IRB Infrastructure', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IRCON', 'IRCON International Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IRCTC', 'IRCTC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IREDA', 'IREDA', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IRFC', 'Indian Railway Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('IRIS', 'IRIS Business Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ISEC', 'ICICI Securities', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ITC', 'ITC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ITCHOTELS', 'ITC Hotels Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ITDCEM', 'ITD Cementation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ITI', 'ITI', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('J&KBANK', 'Jammu & Kashmir Bank Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JAIBALAJI', 'Jai Balaji Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JAINREC', 'Jain Resource Recycling Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JBCHEPHARM', 'JB Chemicals & Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JBMA', 'JBM Auto Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JINDALPOLY', 'Jindal Poly Films', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JINDALSAW', 'Jindal Saw', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JINDALSTEL', 'Jindal Steel & Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JIOFIN', 'Jio Financial Services Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JKCEMENT', 'JK Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JKIL', 'J Kumar Infraprojects', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JKPAPER', 'JK Paper', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JKTYRE', 'JK Tyre & Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JMB', 'JM Financial', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JMFINANCIL', 'JM Financial', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JPASSOCIAT', 'Jaiprakash Associates', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JPPOWER', 'Jaiprakash Power Ventures Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSB', 'Jana Small Finance Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSL', 'Jindal Stainless', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSWCEMENT', 'JSW Cement Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSWDULUX', 'JSW Dulux Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSWENERGY', 'JSW Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSWINFRA', 'JSW Infrastructure Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JSWSTEEL', 'JSW Steel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JUBLFOOD', 'Jubilant Foodworks', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JUBLINGREA', 'Jubilant Ingrevia', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JUBLPHARMA', 'Jubilant Pharmova Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JWL', 'Jupiter Wagons Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JYOTHYLAB', 'Jyothy Labs', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('JYOTICNC', 'Jyoti CNC Automation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KAJARIACER', 'Kajaria Ceramics', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KALYANKJIL', 'Kalyan Jewellers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KANSAINER', 'Kansai Nerolac', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KARURVYSYA', 'Karur Vysya Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KAYNES', 'Kaynes Technology', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KEC', 'KEC International', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KEI', 'KEI Industries Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KFINTECH', 'KFin Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KIMS', 'Krishna Institute of Medical Sciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KIRLOSENG', 'Kirloskar Oil Eng Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KNRCON', 'KNR Constructions', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KOTAKBANK', 'Kotak Mahindra Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KPIL', 'Kalpataru Projects International', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KPITTECH', 'KPIT Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KPRMILL', 'K.P.R. Mill Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KRBL', 'KRBL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KSCL', 'Kaveri Seed Company', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KTIL', 'Kirloskar Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('KTKBANK', 'Karnataka Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LALPATHLAB', 'Dr Lal PathLabs', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LATENTVIEW', 'Latent View Analytics Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LATTEYS', 'Latteys Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LAURUSLABS', 'Laurus Labs', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LAXMIMACH', 'Lakshmi Machine Works', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LEMONTREE', 'Lemon Tree Hotels Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LENSKART', 'Lenskart Solutions Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LGEINDIA', 'LG Electronics India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LICHSGFIN', 'LIC Housing Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LICI', 'LIC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LINDEINDIA', 'Linde India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LLOYDSME', 'Lloyds Metals & Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LODHA', 'Lodha Developers Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LT', 'Larsen & Toubro', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LTF', 'L&T Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LTFOODS', 'LT Foods Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LTM', 'LTM Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LTTS', 'L&T Technology Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LUPIN', 'Lupin', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('LXCHEM', 'Laxmi Organic Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('M&M', 'Mahindra & Mahindra', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('M&MFIN', 'M&M Financial Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAHABANK', 'Bank of Maharashtra', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAHINDCIE', 'Mahindra CIE Automotive', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAHLIFE', 'Mahindra Lifespace', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAHLOG', 'Mahindra Logistics', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MANAPPURAM', 'Manappuram Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MANKIND', 'Mankind Pharma Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAPMYINDIA', 'C.E. Info Systems Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MARICO', 'Marico', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MARUTI', 'Maruti Suzuki', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MASFIN', 'MAS Financial Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAXHEALTH', 'Max Healthcare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MAZDOCK', 'Mazagon Dock Shipbuilders', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MCX', 'MCX', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MEDANTA', 'Global Health (Medanta)', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MEDPLUS', 'Medplus Health Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MEESHO', 'Meesho Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('METROBRAND', 'Metro Brands', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('METROPOLIS', 'Metropolis Healthcare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MFSL', 'Max Financial Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MGL', 'Mahanagar Gas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MIDHANI', 'Mishra Dhatu Nigam', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MINDACORP', 'Minda Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MINDAIND', 'UNO Minda', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MMTC', 'MMTC Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MOLDTKPAC', 'Mold-Tek Packaging', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MOTHERSON', 'Samvardhana Motherson', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MOTILALOFS', 'Motilal Oswal Financial Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MPHASIS', 'Mphasis', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MRF', 'MRF Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MRPL', 'Mangalore Refinery & Petrochemicals Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MSTCLTD', 'MSTC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MSUMI', 'Motherson Sumi Wiring India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MUTHOOTFIN', 'Muthoot Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('MUTHOOTMF', 'Muthoot Microfin', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NACLIND', 'NACL Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NAM-INDIA', 'Nippon Life India Asset Management Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NATCOPHARM', 'Natco Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NATIONALUM', 'National Aluminium', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NAUKRI', 'Info Edge (Naukri)', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NAVA', 'Nava Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NAVINFLUOR', 'Navin Fluorine', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NAVNETEDUL', 'Navneet Education', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NBCC', 'NBCC India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NCC', 'NCC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NESCO', 'Nesco', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NESTLEIND', 'Nestle India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NETWEB', 'Netweb Technologies India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NETWORK18', 'Network18 Media', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NEULANDLAB', 'Neuland Laboratories Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NEWGEN', 'Newgen Software', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NFL', 'National Fertilizers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NH', 'Narayana Hrudayalaya Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NHPC', 'NHPC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NIACL', 'The New India Assurance Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NIITLTD', 'NIIT', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NIVABUPA', 'Niva Bupa Health Insurance Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NLCINDIA', 'NLC India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NMDC', 'NMDC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NSE:CPPLUS', 'Aditya Infotech Ltd', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NSLNISP', 'NINL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NTPC', 'NTPC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NTPCGREEN', 'NTPC Green Energy Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NUVAMA', 'Nuvama Wealth', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NUVOCO', 'Nuvoco Vistas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('NYKAA', 'FSN E-Commerce (Nykaa)', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OBEROIRLTY', 'Oberoi Realty', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OCCL', 'Oriental Carbon & Chemicals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OFSS', 'Oracle Financial Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OIL', 'Oil India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OLAELEC', 'Ola Electric Mobility Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OLECTRA', 'Olectra Greentech', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('OMAXE', 'Omaxe', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ONESOURCE', 'Onesource Specialty Pharma Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ONGC', 'ONGC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ORIENTCEM', 'Orient Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ORIENTELEC', 'Orient Electric', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ORIENTPPR', 'Orient Paper & Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PAGEIND', 'Page Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PARADEEP', 'Paradeep Phosphates Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PASHUPATI', 'Pashupati Cotspin', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PATANJALI', 'Patanjali Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PAYTM', 'One 97 Communications (Paytm)', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PCBL', 'PCBL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PDMJEPAPER', 'Pudumjee Paper Products', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PEL', 'Piramal Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PERSISTENT', 'Persistent Systems', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PETRONET', 'Petronet LNG', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PFC', 'Power Finance Corporation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PFIZER', 'Pfizer Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PFOCUS', 'Prime Focus Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PGEL', 'PG Electroplast Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PGHH', 'Procter & Gamble Hygiene', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PGINVIT', 'Powergrid Infrastructure Investment Trust', 'BSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PHOENIXLTD', 'Phoenix Mills', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PIDILITIND', 'Pidilite Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PIIND', 'PI Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PILANIINVS', 'Pilani Investment', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PINELABS', 'Pine Labs Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PIRAMALFIN', 'Piramal Finance Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PNB', 'Punjab National Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PNBHOUSING', 'PNB Housing Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POLICYBZR', 'PB Fintech Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POLYCAB', 'Polycab India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POLYMED', 'Poly Medicure', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POONAWALLA', 'Poonawalla Fincorp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POWERGRID', 'Power Grid Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('POWERINDIA', 'Hitachi Energy India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PPLPHARMA', 'Piramal Pharma Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PRAJIND', 'Praj Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PREMIERENE', 'Premier Energies Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PRESTIGE', 'Prestige Estates', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PRINCEPIPE', 'Prince Pipes & Fittings', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PRSMJOHNSN', 'Prism Johnson', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PRUDENT', 'Prudent Corporate Advisory', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PSPPROJECT', 'PSP Projects', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PTCIL', 'PTC Industries Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PVRINOX', 'PVR Inox', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('PWL', 'Physicswallah Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('QUESS', 'Quess Corp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RADICO', 'Radico Khaitan', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAILTEL', 'RailTel Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAINBOW', 'Rainbow Childrens Medicare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAJESHEXPO', 'Rajesh Exports', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAJRATAN', 'Rajratan Global Wire', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAMCOCEM', 'Ramco Cements', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RATNAMANI', 'Ratnamani Metals & Tubes', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RAYMOND', 'Raymond', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RBLBANK', 'RBL Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RCF', 'Rashtriya Chemicals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RECLTD', 'REC Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('REDINGTON', 'Redington', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RELAXO', 'Relaxo Footwears', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RELIANCE', 'Reliance Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RELIGARE', 'Religare Enterprises', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RELINFRA', 'Reliance Infrastructure', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RESPONIND', 'Responsive Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RHIM', 'RHI Magnesita India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RITES', 'RITES', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RKFORGE', 'Ramkrishna Forgings Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ROSSARI', 'Rossari Biotech', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ROUTE', 'Route Mobile', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RPGLIFE', 'RPG Life Sciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RPOWER', 'Reliance Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RPPL', 'Rajshree Polypack', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RRKABEL', 'RR Kabel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('RVNL', 'Rail Vikas Nigam', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SADBHAV', 'Sadbhav Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAFARI', 'Safari Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAGILITY', 'Sagility Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAIL', 'Steel Authority of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAILIFE', 'Sai Life Sciences Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAMMAANCAP', 'Sammaan Capital Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SANOFI', 'Sanofi India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAPPHIRE', 'Sapphire Foods', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SARDAEN', 'Sarda Energy & Minerals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SAREGAMA', 'Saregama India Ltd', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SBFC', 'SBFC Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SBICARD', 'SBI Cards', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SBILIFE', 'SBI Life Insurance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SBIN', 'State Bank of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SCHAEFFLER', 'Schaeffler India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SCHNEIDER', 'Schneider Electric Infrastructure Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SCI', 'Shipping Corporation of India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SENCO', 'Senco Gold', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SEQUENT', 'Sequent Scientific', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SFL', 'Sheela Foam', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHANKARA', 'Shankara Building Products', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHARDACROP', 'Sharda Cropchem', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHILPAMED', 'Shilpa Medicare', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHOPERSTOP', 'Shoppers Stop', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHREDIGCEM', 'Shree Digvijay Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHREECEM', 'Shree Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHRIRAMFIN', 'Shriram Finance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SHYAMMETL', 'Shyam Metalics and Energy Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SIEMENS', 'Siemens', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SIGNATURE', 'Signatureglobal (India) Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SJVN', 'SJVN Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SKFINDIA', 'SKF India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SMLISUZU', 'SML Isuzu', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SOBHA', 'Sobha', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SOLARA', 'Solara Active Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SOLARINDS', 'Solar Industries India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SONACOMS', 'Sona BLW Precision', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SONATSOFTW', 'Sonata Software Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SPANDANA', 'Spandana Sphoorty', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SPARC', 'Sun Pharma Advanced Research', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SPLPETRO', 'Selan Exploration', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SPORTKING', 'Sportking India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SREEL', 'Sreeleathers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SRF', 'SRF', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SSWL', 'Steel Strips Wheels', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('STARCEMENT', 'Star Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('STARHEALTH', 'Star Health Insurance', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('STLTECH', 'Sterlite Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('STRTECH', 'Stride Shasun', 'NSE', 'f');
insert into universe (ticker, stock_name, exchange, active) values ('SUBEXLTD', 'Subex', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUMICHEM', 'Sumitomo Chemical India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUNDARMFIN', 'Sundaram Finance Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUNPHARMA', 'Sun Pharmaceutical', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUNTV', 'Sun TV Network', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUPREMEIND', 'Supreme Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUPRIYA', 'Supriya Lifescience', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SURYAROSNI', 'Surya Roshni', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUVEN', 'Suven Pharmaceuticals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUVENPHAR', 'Suven Life Sciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SUZLON', 'Suzlon Energy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SWANCORP', 'Swan Corp Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SWIGGY', 'Swiggy', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SWSOLAR', 'Sterling and Wilson Solar', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SYMPHONY', 'Symphony', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SYNGENE', 'Syngene International Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('SYRMA', 'Syrma SGS Technology', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TANLA', 'Tanla Platforms', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TARIL', 'Transformers And Rectifiers (India)', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATACAP', 'Tata Capital Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATACHEM', 'Tata Chemicals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATACOMM', 'Tata Communications', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATACONSUM', 'Tata Consumer Products', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATAELXSI', 'Tata Elxsi', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATAINVEST', 'Tata Investment Corporation Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATAMOTORS', 'Tata Motors', 'NSE', 'f');
insert into universe (ticker, stock_name, exchange, active) values ('TATAPOWER', 'Tata Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATASTEEL', 'Tata Steel', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATATECH', 'Tata Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TATVA', 'Tatva Chintan Pharma', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TBOTEK', 'TBO Tek Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TCNSBRANDS', 'TCNS Clothing', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TCS', 'Tata Consultancy Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TDPOWERSYS', 'TD Power Systems', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TEAMLEASE', 'TeamLease Services', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TECHM', 'Tech Mahindra Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TECHNOE', 'Techno Electric & Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TEGA', 'Tega Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TEJASNET', 'Tejas Networks', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TENNIND', 'Tenneco Clean Air India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TEXRAIL', 'Texmaco Rail & Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TFCILTD', 'Tourism Finance Corporation', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('THANGAMAYL', 'Thangamayil Jewellery', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('THELEELA', 'Leela Palaces Hotels & Resorts Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('THERMAX', 'Thermax', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('THYROCARE', 'Thyrocare Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TIINDIA', 'Tube Investments of India Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TIMETECHNO', 'Time Technoplast', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TIMKEN', 'Timken India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TITAGARH', 'Titagarh Rail Systems Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TITAN', 'Titan Company', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TMCV', 'Tata Motors Limited', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TMPV', 'Tata Motors Passenger Vehicles Limited', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TNPL', 'Tamil Nadu Newsprint', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TORNTPHARM', 'Torrent Pharmaceuticals', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TORNTPOWER', 'Torrent Power', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TPLPLASTEH', 'TPL Plastech', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TRAVELFOOD', 'Travel Food Services Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TRENT', 'Trent', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TRIDENT', 'Trident', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TRITURBINE', 'Triveni Turbine', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TRIVENI', 'Triveni Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TTML', 'Tata Teleservices (Maharashtra) Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('TVSMOTOR', 'TVS Motor Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UBL', 'United Breweries Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UCOBANK', 'UCO Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UFLEX', 'Uflex', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UJJIVANSFB', 'Ujjivan Small Finance Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ULTRACEMCO', 'UltraTech Cement', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UNIONBANK', 'Union Bank of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UNITDSPR', 'United Spirits', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UNOMINDA', 'UNO Minda', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UPL', 'UPL', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('URBANCO', 'Urban Company Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('USHAMART', 'Usha Martin Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UTIAMC', 'UTI AMC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('UTIAMCLTD', 'UTI AMC', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VAIBHAVGBL', 'Vaibhav Global', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VARROC', 'Varroc Engineering', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VBL', 'Varun Beverages', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VEDL', 'Vedanta', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VGUARD', 'V-Guard Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VIJAYA', 'Vijaya Diagnostic Centre Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VINATIORGA', 'Vinati Organics', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VIPIND', 'VIP Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VMART', 'V-Mart Retail', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VMM', 'Vishal Mega Mart Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VOLTAMP', 'Voltamp Transformers', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VOLTAS', 'Voltas', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VSTIND', 'VST Industries', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('VTL', 'Vardhman Textiles Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WAAREEENER', 'Waaree Energies Ltd.', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WELCORP', 'Welspun Corp', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WELSPUNLIV', 'Welspun Living', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WESTLIFE', 'Westlife Foodworld', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WHIRLPOOL', 'Whirlpool of India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WIPRO', 'Wipro', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('WOCKPHARMA', 'Wockhardt', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('XCHANGING', 'Xchanging Solutions', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('YESBANK', 'Yes Bank', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZEEL', 'Zee Entertainment', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZENSARTECH', 'Zensar Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZENTEC', 'Zen Technologies', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZFCVINDIA', 'ZF Commercial Vehicle Control Systems India', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZODIACLOTH', 'Zodiac Clothing', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZYDUSLIFE', 'Zydus Lifesciences', 'NSE', 't');
insert into universe (ticker, stock_name, exchange, active) values ('ZYDUSWELL', 'Zydus Wellness Ltd.', 'NSE', 't');
